eureka:
  instance:
    prefer-ip-address: true
  client:  
    register-with-eureka: true 
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
spring: 
  zipkin:
    base-url: http://zipkin-svc:9411
